// <auto-generated />
using System;
using Hackfest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackfest.Migrations
{
    [DbContext(typeof(ContexteBD))]
    [Migration("20181122143754_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hackfest.Models.Réponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Courriel")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<bool?>("SeraPrésent")
                        .IsRequired();

                    b.Property<string>("Téléphone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Réponses");
                });
#pragma warning restore 612, 618
        }
    }
}
