// <auto-generated />
using System;
using Hackfest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackfest.Migrations
{
    [DbContext(typeof(ContexteTP))]
    partial class ContexteBDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hackfest.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Affiliation")
                        .IsRequired();

                    b.Property<string>("Courriel")
                        .IsRequired();

                    b.Property<DateTime>("DateInscription");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<string>("Prénom")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Réponses");
                });
#pragma warning restore 612, 618
        }
    }
}
